server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: postgres
    password: ROOT

mybatis-plus:
  check-config-location: true  #启动时检查mybatis xml 文件的存在
  executor-type: reuse  #复用预处理语句
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名规则
    auto-mapping-unknown-column-behavior: warning #自动映射未知列或未知属性处理策略，以日志打印警告信息
    cache-enabled: true #全局开启所有映射器已经配置好的任何缓存
    call-setters-on-nulls: false #指定当结果集中值为null时不调用映射对象的serrer
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql到控制台
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1 #逻辑已删除（默认为1）
      logic-not-delete-value: 0 #逻辑未删除（默认为0）
  mapper-locations: classpath:/mapper/**/*Mapper.xml